"""initial_migration_with_all_tables

Revision ID: 4ccb20e2177b
Revises: 364cfef001b8
Create Date: 2025-12-03 05:40:39.350263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ccb20e2177b'
down_revision: Union[str, None] = '364cfef001b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
