"""add_role_and_warehouse_support

Revision ID: 86598ce53e47
Revises: 4ccb20e2177b
Create Date: 2025-12-03 06:50:53.733132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86598ce53e47'
down_revision: Union[str, None] = '4ccb20e2177b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create UserRole enum type
    userrole_enum = sa.Enum('SUPER_ADMIN', 'WAREHOUSE', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('warehouses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )

    # Add new columns to users table first (before inventory_items to avoid FK issues)
    op.add_column('users', sa.Column('role', userrole_enum, nullable=True))  # Temporarily nullable
    op.add_column('users', sa.Column('warehouse_id', sa.String(), nullable=True))

    # Set default role for existing users
    op.execute("UPDATE users SET role = 'WAREHOUSE' WHERE role IS NULL")

    # Now make role NOT NULL
    op.alter_column('users', 'role', nullable=False)

    op.create_foreign_key(None, 'users', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')

    # Now handle inventory_items changes
    op.add_column('inventory_items', sa.Column('sku', sa.String(), nullable=True))  # Temporarily nullable
    op.add_column('inventory_items', sa.Column('unit_price', sa.Float(), nullable=True))  # Temporarily nullable
    op.add_column('inventory_items', sa.Column('warehouse_id', sa.String(), nullable=True))  # Temporarily nullable

    # Set default values for existing rows if any
    op.execute("UPDATE inventory_items SET sku = 'SKU-' || id::text WHERE sku IS NULL")
    op.execute("UPDATE inventory_items SET unit_price = COALESCE(price, 0.0) WHERE unit_price IS NULL")

    # Now alter column types and constraints
    op.alter_column('inventory_items', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               postgresql_using='id::text')
    op.alter_column('inventory_items', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inventory_items', 'min_stock_level',
               existing_type=sa.INTEGER(),
               nullable=False)

    # Make columns NOT NULL after setting defaults
    op.alter_column('inventory_items', 'sku', nullable=False)
    op.alter_column('inventory_items', 'unit_price', nullable=False)

    op.drop_index('ix_inventory_items_id', table_name='inventory_items')
    op.create_index(op.f('ix_inventory_items_sku'), 'inventory_items', ['sku'], unique=True)
    op.create_index(op.f('ix_inventory_items_warehouse_id'), 'inventory_items', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'inventory_items', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    op.drop_column('inventory_items', 'warehouse')
    op.drop_column('inventory_items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses_backup',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.add_column('inventory_items', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('inventory_items', sa.Column('warehouse', sa.VARCHAR(), server_default=sa.text("'main'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inventory_items', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_items_warehouse_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_sku'), table_name='inventory_items')
    op.create_index('ix_inventory_items_id', 'inventory_items', ['id'], unique=False)
    op.alter_column('inventory_items', 'min_stock_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory_items', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inventory_items', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='id::integer')
    op.drop_column('inventory_items', 'unit_price')
    op.drop_column('inventory_items', 'sku')
    op.drop_column('inventory_items', 'warehouse_id')

    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'warehouse_id')
    op.drop_column('users', 'role')

    op.drop_table('warehouses')

    # Drop the enum type
    userrole_enum = sa.Enum('SUPER_ADMIN', 'WAREHOUSE', name='userrole')
    userrole_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
